### ISSUE TITLE
Question: Does VSCode actually use/support supportsValueFormattingOptions

### ISSUE THREAD

**Issue by haneefdm** [microsoft/VSDebugAdapterHost#10]
I see it in the protocol and documented in detail [here](https://github.com/microsoft/VSDebugAdapterHost/wiki/Stack-Trace-and-Value-Formatting) 

But I have no evidence of it (only tried variables-request) being used/supplied in my Debug-Adapter. I searched VSCode source code and did not find any references to `supportsValueFormattingOptions`. I have requests for supporting it for our debugger but I don't think it is possible. Am I wrong?

I apologize if I posted it in the wrong repo.

**Comment by gregg-miskelly** [comment]
This is probably a better question for the VS Code team, but I am about 99% certain that VS code doesn't ever provide value formatting options. Full Visual Studio does, but VS Code does not (unless they added support for it recently without telling us).
