### ISSUE TITLE
Using the Sample Debug Adapter with VS Code

### ISSUE THREAD

**Issue by Elias-Johansson** [microsoft/VSDebugAdapterHost#14]
Hello,

could you clarify whether it is possible to use the Sample Debug Adapter with VS Code instead of VS? Please share your tips on writing the corresponding VS Code extension if it is possible.

--
Thanks Elias.

**Comment by andrewcrawley** [comment]
Hi, Elias

As far as I know, nobody has tried it, but I can't think of any reason it wouldn't work.  You'd need to install Mono or something if you're planning on doing this on a non-Windows platform.  The C++ extension for VS Code uses a debug adapter based on this same framework - you can find the extension source here: https://github.com/microsoft/vscode-cpptools/tree/master/Extension and the debug adapter source here: https://github.com/microsoft/MIEngine/tree/master/src/OpenDebugAD7

Thanks

Andrew

**Comment by Elias-Johansson** [comment]
Hi Andrew,

> As far as I know, nobody has tried it, but I can't think of any reason it wouldn't work.
I'm planning to do this on a Windows platform. As far as I understand, the VS Code extension should mimic the Engine Launcher to communicate with SampleDebugAdapter.exe.

I'm planning to do this on a Windows platform. As far as I understand, the VS Code extension should mimic the Engine Launcher to communicate with SampleDebugAdapter.exe.

> You'd need to install Mono or something if you're planning on doing this on a non-Windows platform. The C++ extension for VS Code uses a debug adapter based on this same framework - you can find the extension source here: https://github.com/microsoft/vscode-cpptools/tree/master/Extension and the debug adapter source here: https://github.com/microsoft/MIEngine/tree/master/src/OpenDebugAD7

Thanks. I'll try to figure it out.

--
Best,
Elias
