### ISSUE TITLE
No support for WriteMemory Requests

### ISSUE THREAD

**Issue by charlzmerth** [microsoft/VSDebugAdapterHost#16]
There doesn't seem to be virtual methods in DebugAdapterBase or DebugAdapterHostBase relating to [WriteMemory Request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_WriteMemory).

![image](https://user-images.githubusercontent.com/22756165/131557378-d57af94d-6b90-4a42-9fef-4a4489b1707b.png)

This is observed in **16.1.50204.1** (the latest available in NuGet).

**Comment by andrewcrawley** [comment]
I just pushed version 17.0.50801.1, which contains all protocol changes to this date.  It should be available on NuGet shortly.
