### ISSUE TITLE
"EngineGuid" argument for DebugAdapterHost.Launch

### ISSUE THREAD

**Issue by AndreiKrutikov** [Microsoft/VSDebugAdapterHost#3]
Visual Studio 15.5.7
In EngineLauncher there are using 

https://github.com/Microsoft/VSDebugAdapterHost/blob/9b1a0c67a66c4b5792dae8b96a17f05cc70a266a/src/tools/EngineLauncher/LaunchEngineCommand.cs#L89

 parameter for "DebugAdapterHost.Launch" which causes error.
`>DebugAdapterHost.Launch /LaunchJson:"C:\Users\Andrei\launch.json" /EngineGuid:"facadeaa-dd82-4f36-92c4-e0d9615f0eb6"`
`"/EngineGuid" is not a valid switch for this command.`

VS offers only /LaunchJson and /ConfigurationName as parameters.

-------------------------------------
Two unrelated questions:
1)Is there a way to launch DebugAdapterHost without passing a path to json, but rather just with arguments?
2)How exactly to specify in launch.json to use DE with specific GUID?

**Comment by andrewcrawley** [comment]
Hi, Andrei

The `EngineGuid` parameter was added in VS 15.6 Preview 2.  You'll need that version (or newer) to use the VS Debug Adapter Host.

In answer to your other questions:

1) Using the `DebugAdapterHost.Launch` command (or the EngineLauncher addin), you have to specify a launch.json on disk.  If you have your own VS project system or another addin, you can launch using [IVSDebugger4.LaunchDebugTargets4](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsdebugger4.launchdebugtargets4?view=visualstudiosdk-2017) - specify your engine guid for `guidLaunchDebugEngine`, the target process name for `bstrExe`, and the launch.json content in `bstrOptions`.
2) The engine guid is not specified in launch.json - if you use the EngineLauncher addin, you can pick it from the "Debug engine" dropdown, or if you're launching via your own mechanism, you can provide the guid as described above.

**Comment by AndreiKrutikov** [comment]
Thank you very much for your answers!
