### ISSUE TITLE
EvaluateArguments.ContextValue Missing Values

### ISSUE THREAD

**Issue by wyatcall** [microsoft/VSDebugAdapterHost#31]
I'm not sure if this is the right place, but it is where the [Nuget Package](https://www.nuget.org/packages/Microsoft.VisualStudio.Shared.VsCodeDebugProtocol) points to.

`EvaluateArguments.ContextValue` is missing the following items as provided in the [Debug Adapter Protocol Specification](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate):
 - clipboard
 - variables

This will causes a `JsonSerializationException` and I haven't figured out how to recover from it yet.

**Comment by andrewcrawley** [comment]
Thanks for the report - we've just published version 17.10.10123.1 of the protocol library to NuGet, which should contain all the latest DAP updates.

**Comment by wyatcall** [comment]
Thank you!
