### ISSUE TITLE
Contact email rejected

### ISSUE THREAD

**Issue by softwarecraft** [Microsoft/VSDebugAdapterHost#4]
Hi, the contact email in the Readme file vsdahfeed@microsoft.com rejected my msg with this advisory: 

> Office 365
> Your message to pinezorro@microsoft.com couldn't be delivered.
> The group pinezorro only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

Can you provide an alternate?

**Comment by andrewcrawley** [comment]
Looks like I had an incorrect setting on that mail account - I've fixed it, but it may take some time for the new settings to take effect.  I'll resolve this issue once I've verified that external messages no longer bounce.

Until then, you can contact me directly with feedback, questions, or comments: andrewcr@microsoft.com.

**Comment by andrewcrawley** [comment]
Looks like this is working properly now.  Thanks for letting us know!
