### ISSUE TITLE
watch doesn't show referenced child variables on the tree view.

### ISSUE THREAD

**Issue by phoityne** [Microsoft/VSDebugAdapterHost#5]
Hi.
I'm trying to run [Haskell debug adapter](https://github.com/phoityne/hdx4vs) on VisualStudio2017.

It starts running same as VSCode,
but there is a [problem on watch functionality](https://github.com/phoityne/hdx4vs/issues/1).
watch doesn't show referenced child variables on the tree view.

VS does not send EvaluateRequest when adding local variable to watch, but VSCode does.
VSCode sends EvaluateRequest with context "watch".

Could you send EvaluateRequest same with VSCode when adding variable to watch ?
Any advice will be appreciated.

Best Regards.

**Comment by andrewcrawley** [comment]
Hi,

This should work as expected if you set the `variablesReference` fields in your response to the `variables` request when a variable has children.  This will also fix the issue I noticed in the linked bug where the item in the "Locals" window in VS Code doesn't appear expandable, but the same item added to the "Watch" window does.

The reason for this is that items in the Watch window in VS can be editable (they're read-only in VS Code).  To support this without requiring changes to debug adapters, when something is added to the Watch window, we first issue a `variables` request to see if the item being added is a variable - this allows us to use the `setVariable` request to update the value later.  If you want to fully support this scenario in VS, consider implementing our extra `setExpression` request as documented [here](https://github.com/Microsoft/VSDebugAdapterHost/wiki/Editable-'Watch'-Window-Values).  If your adapter supports this request, we'll send an `evaluate` request when an item is added to the "Watch" window, and a `setExpression` request when the value is modified.

Let me know if I can provide additional information!

**Comment by phoityne** [comment]
Thank you for the information.
I'm going to set reference attribute of the VariablesResponse for the local variables.
(actually, [it works well.](https://github.com/phoityne/hdx4vs/issues/1#issuecomment-397842766))
