### ISSUE TITLE
Hitting "Value was either too large or too small for an Int32." after the host sends setBreakpoint

### ISSUE THREAD

**Issue by lanza** [Microsoft/VSDebugAdapterHost#7]
After this request is sent and before the debug adapter responds I'm seeing a popup dialog saying "Value was either too large or too small for an Int32" at which point the host crashes. Is there any way to see what's going on within the host to debug this error?

**Comment by gregg-miskelly** [comment]
I would suggest first starting by turning on logging (see https://github.com/Microsoft/VSDebugAdapterHost/wiki/Logging) and look for numeric fields returned by the debugger with a value outside of the range of 32-bit integer. There are additional troubleshooting steps you can take next, but looking at the logs is probably the easiest thing.

**Comment by lanza** [comment]
So it turns out the Visual Studio host uses 32 bit integers for breakpoint/stack/etc IDs. Is this a bug on VS's side or a
