### ISSUE TITLE
Should Stack frame ID type be int32 or int64?

### ISSUE THREAD

**Issue by lextm** [Microsoft/VSDebugAdapterHost#8]
The protocol itself uses `number`, https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame

And `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` uses int32, which is what Microsoft implementations like vsdbg match.

However, there are other debuggers that use int64, such as Samsung's .NET Core debugger, https://github.com/Samsung/netcoredbg/issues/19. `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` cannot handle the large IDs returned from such debuggers, and simply crash.

Is there a solution out there? Is it possible to change `Microsoft.VisualStudio.Shared.VsCodeDebugProtocol` to use int64?

**Comment by gregg-miskelly** [comment]
Using `int64` is a bug waiting to happen -- Javascript only supports 52-bit numbers. Generally the reason why one would want to make it an `int64` is to store a pointer value. But that will stop working once you debug a large application that results in pointers >= 2^52-1. So I would generally suggest that all of the `Number` ids in the protocol should be maintained using a handle collection which ensures that all ids are >= 1 and <= int.MaxValue.

**Comment by lextm** [comment]
Thanks for the confirmation. Samsung guys will revise their debugger to use int32 to be compliant to the standard.
