### ISSUE TITLE
Debug Adapter doesn't open properly

### ISSUE THREAD

**Issue by Nate-Brown-Bose** [microsoft/VSDebugAdapterHost#9]
When I try to debug my project, the Debug Adapter claims to be launching, but then opens and closes resulting with a popup error claiming "Object reference not set to an instance of an object". Once I close out of it, the debug output in Visual Studio reads "The program 'python.exe' has exited with code -1 (0xffffffff)". I have not been able to find help anywhere on this and need to know if it's something in my code or in my Visual Studio downloads. I am using env(3.7, 64-bit) to run my code.

**Comment by andrewcrawley** [comment]
Can you follow the instructions to turn on logging (https://github.com/microsoft/VSDebugAdapterHost/wiki/Logging) and paste your log here?

The contents of your pkgdef (if you have one) and launch.json would also be helpful.

**Comment by Nate-Brown-Bose** [comment]
Here's the log after running the adapter:

 1> DebugAdapterHost version: 16.2.30627.1 commit:6ca161c0da49cefd8f25e874bbba7ae8e2c50339
 1> ERROR: Unexpected error

NullReferenceException: Object reference not set to an instance of an object.

Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.Engine.Implementation.DebuggedProcess.InitializeDebugAdapter(LaunchConfiguration launchJson)
Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.Engine.Implementation.DebuggedProcess.StartDebugAdapter(IAdapterLaunchInfo launchInfo, ITargetHostInterop targetInterop)

 1> ERROR: Object reference not set to an instance of an object.


As for the package I'm using conda so my packages include numpy, pandas, openssl, pip, SQLite, setuptools and a few more. 

I cannot find the launch.json file that's needed for the debugging process. If it helps, I was unaware that I had to edit that file in the first place in order to use the debugger, so I'd never thought to look for it before now. I've looked in My local appdata and there is no .vscode folder, or Code folder so I'm not sure if I even have launch.json.

**Comment by gregg-miskelly** [comment]
Sorry for the delay, Andrew is on vacation.

First, are you developing a debug adapter? Or are you just trying to use the Python debugger?

**Comment by Nate-Brown-Bose** [comment]
I believe I'm trying to use the python debugger. And no worries.

**Comment by int19h** [comment]
Issue moved to [microsoft/PTVS #5610](https://github.com/microsoft/PTVS/issues/5610) via [**ZenHub**](https://www.zenhub.com/)

**Comment by int19h** [comment]
It's definitely an issue specific to the debug adapter in PTVS, so I moved it to that repo, and we'll follow up there. Feel free to close it on this end.
